fail_modules.ml[4:9 ..4:9]: Variable not in scope: `x`
  Â· Arising from use of  `x`
